## conda environment for reproducibility

name: scalable-ct
channels:
  - conda-forge

dependencies:
  - python=3.9
  - pip>=24.0
  # - pyradiomics
  - mkdocs
  - mkdocs-material


  # core
  - numpy>=1.26
  - pandas>=2.2
  - scipy>=1.12
  - scikit-learn>=1.4

  # imaging
  - simpleitk>=2.3
  - pydicom>=2.4
  - nibabel>=5.2
  - scikit-image>=0.22
  - pillow
  - opencv
  - imagecodecs

  # distributed
  - dask
  - distributed
  - dask-image
  - zarr
  - numcodecs
  - fsspec
  - s3fs

  # notebooks
  - jupyterlab
  - ipykernel
  - matplotlib
  - seaborn
  - plotly
  - tqdm
  - ipywidgets

  # dev tools
  - pytest
  - black
  - isort
  - pre-commit
  - rich
  - pyyaml
  - click
  - loguru
